# A conda environment for CSDMS Workbench software.
name: csdms
channels:
  - conda-forge
dependencies:
  - python =3
  - pip
  - bmi-geotiff
  - bmi-topography
  - bmi-tester
  - bmi-wavewatch3
  - bmipy
  - landlab >=2.7
  - pymt >=1.3
  - pip:
    - -r requirements.txt
